### ISSUE TITLE
建议增加CMakelists.txt

### ISSUE THREAD

**Issue by Lost-Temple** [primihub/primihub#360]
我在阅读代码中，使用CLion时，安装Bazel插件，但这个插件对于网络代理好像有点缺陷。如果能使用CMakelists.txt，CLion会适配得比较好。对于代码高亮，引用的跳转都会比较方便。VS CODE下，也是多多少少有点类似的问题。（也有可能是我本身的开发环境设置的问题。）

**Comment by phoenix20162016** [comment]
thanks for your advice, as you know, to maintain a large project, we need to chose a good tools, maybe bazel is a better choice,
as mentioned, vs code has some drawback when we use it to jump during reading code, maybe really some setting is not properly correct, such as, the match rule you can use pattern match instead of default,
and meanwhile, we will consider supporting cmake after we evaluate it
